//
//  Constants.h
//  ColorApp
//
//  Created by Michael Berg on 7/7/15.
//  Copyright (c) 2015 Michael Berg. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constants : NSObject

FOUNDATION_EXPORT NSString *const COLOR_MENU_TITLE;
FOUNDATION_EXPORT NSString *const COLOR_PICKER_TITLE;
FOUNDATION_EXPORT NSString *const SAVED_COLORS_TITLE;
FOUNDATION_EXPORT NSString *const LOAD_COLORS_TITLE;
FOUNDATION_EXPORT NSString *const COLOR_EXTRACTOR_TITLE;
FOUNDATION_EXPORT NSString *const COLOR_OPTIONS_TITLE;

FOUNDATION_EXPORT NSString *const COLOR_MENU_STARTER_TIP;
FOUNDATION_EXPORT NSString *const COLOR_PICKER_STARTER_TIP;
FOUNDATION_EXPORT NSString *const SAVED_COLORS_STARTER_TIP;
FOUNDATION_EXPORT NSString *const LOAD_COLORS_STARTER_TIP;
FOUNDATION_EXPORT NSString *const COLOR_EXTRACTOR_STARTER_TIP;
FOUNDATION_EXPORT NSString *const COLOR_OPTIONS_STARTER_TIP;

@end
