//
//  Constants.h
//  ColorApp
//
//  Created by Michael Berg on 7/7/15.
//  Copyright (c) 2015 Michael Berg. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constants : NSObject

#pragma mark -- User Default String variable declarations

FOUNDATION_EXPORT NSString *const USER_DEFAULT_SHOW_NEW_USER_TIP;

#pragma mark -- VC Title String variable declarations

FOUNDATION_EXPORT NSString *const COLOR_MENU_TITLE;
FOUNDATION_EXPORT NSString *const COLOR_PICKER_TITLE;
FOUNDATION_EXPORT NSString *const SAVED_COLORS_TITLE;
FOUNDATION_EXPORT NSString *const LOAD_COLORS_TITLE;
FOUNDATION_EXPORT NSString *const COLOR_EXTRACTOR_TITLE;
FOUNDATION_EXPORT NSString *const COLOR_OPTIONS_TITLE;

#pragma mark -- Tip String variable declaractions

FOUNDATION_EXPORT NSString *const COLOR_MENU_TIP_1;
FOUNDATION_EXPORT NSString *const COLOR_MENU_TIP_2;
FOUNDATION_EXPORT NSString *const COLOR_MENU_TIP_3;
FOUNDATION_EXPORT NSString *const COLOR_MENU_TIP_4;

FOUNDATION_EXPORT NSString *const COLOR_PICKER_TIP_1;
FOUNDATION_EXPORT NSString *const COLOR_PICKER_TIP_2;
FOUNDATION_EXPORT NSString *const COLOR_PICKER_TIP_3;
FOUNDATION_EXPORT NSString *const COLOR_PICKER_TIP_4;

FOUNDATION_EXPORT NSString *const SAVED_COLORS_TIP_1;
FOUNDATION_EXPORT NSString *const SAVED_COLORS_TIP_2;

FOUNDATION_EXPORT NSString *const LOAD_COLORS_TIP_1;
FOUNDATION_EXPORT NSString *const LOAD_COLORS_TIP_2;

FOUNDATION_EXPORT NSString *const COLOR_EXTRACTOR_TIP_1;
FOUNDATION_EXPORT NSString *const COLOR_EXTRACTOR_TIP_2;
FOUNDATION_EXPORT NSString *const COLOR_EXTRACTOR_TIP_3;

FOUNDATION_EXPORT NSString *const COLOR_OPTIONS_TIP_1;
FOUNDATION_EXPORT NSString *const COLOR_OPTIONS_TIP_2;

@end
